/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as SettingsNicknameRouteImport } from './routes/settings/nickname'
import { Route as SettingsMuteChatRouteImport } from './routes/settings/mute-chat'
import { Route as ChatsChar91chatIdChar93RouteImport } from './routes/chats/[chatId]'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthVerifyEmailTokenRouteImport } from './routes/auth/verify-email.$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password.$token'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNicknameRoute = SettingsNicknameRouteImport.update({
  id: '/settings/nickname',
  path: '/settings/nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMuteChatRoute = SettingsMuteChatRouteImport.update({
  id: '/settings/mute-chat',
  path: '/settings/mute-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsChar91chatIdChar93Route = ChatsChar91chatIdChar93RouteImport.update({
  id: '/chats/[chatId]',
  path: '/chats/[chatId]',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailTokenRoute = AuthVerifyEmailTokenRouteImport.update({
  id: '/auth/verify-email/$token',
  path: '/auth/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chats/[chatId]': typeof ChatsChar91chatIdChar93Route
  '/settings/mute-chat': typeof SettingsMuteChatRoute
  '/settings/nickname': typeof SettingsNicknameRoute
  '/chats': typeof ChatsIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chats/[chatId]': typeof ChatsChar91chatIdChar93Route
  '/settings/mute-chat': typeof SettingsMuteChatRoute
  '/settings/nickname': typeof SettingsNicknameRoute
  '/chats': typeof ChatsIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chats/[chatId]': typeof ChatsChar91chatIdChar93Route
  '/settings/mute-chat': typeof SettingsMuteChatRoute
  '/settings/nickname': typeof SettingsNicknameRoute
  '/chats/': typeof ChatsIndexRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
  '/auth/verify-email/$token': typeof AuthVerifyEmailTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/chats/[chatId]'
    | '/settings/mute-chat'
    | '/settings/nickname'
    | '/chats'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/chats/[chatId]'
    | '/settings/mute-chat'
    | '/settings/nickname'
    | '/chats'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/chats/[chatId]'
    | '/settings/mute-chat'
    | '/settings/nickname'
    | '/chats/'
    | '/auth/reset-password/$token'
    | '/auth/verify-email/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ChatsChar91chatIdChar93Route: typeof ChatsChar91chatIdChar93Route
  SettingsMuteChatRoute: typeof SettingsMuteChatRoute
  SettingsNicknameRoute: typeof SettingsNicknameRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
  AuthVerifyEmailTokenRoute: typeof AuthVerifyEmailTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/nickname': {
      id: '/settings/nickname'
      path: '/settings/nickname'
      fullPath: '/settings/nickname'
      preLoaderRoute: typeof SettingsNicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mute-chat': {
      id: '/settings/mute-chat'
      path: '/settings/mute-chat'
      fullPath: '/settings/mute-chat'
      preLoaderRoute: typeof SettingsMuteChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/[chatId]': {
      id: '/chats/[chatId]'
      path: '/chats/[chatId]'
      fullPath: '/chats/[chatId]'
      preLoaderRoute: typeof ChatsChar91chatIdChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/$token': {
      id: '/auth/verify-email/$token'
      path: '/auth/verify-email/$token'
      fullPath: '/auth/verify-email/$token'
      preLoaderRoute: typeof AuthVerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ChatsChar91chatIdChar93Route: ChatsChar91chatIdChar93Route,
  SettingsMuteChatRoute: SettingsMuteChatRoute,
  SettingsNicknameRoute: SettingsNicknameRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
  AuthVerifyEmailTokenRoute: AuthVerifyEmailTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
